export default {
  acRepairing: {
    en: "- AC Diagnosis and Troubleshooting:* Our technicians have a keen eye for identifying AC issues and providing accurate diagnoses, saving you time and money on unnecessary repairs.\n- Precision Repairs: From fixing refrigerant leaks to replacing faulty components, our technicians execute repairs with precision and attention to detail, ensuring long-lasting results.\n- Preventive Maintenance: We believe in proactive care for your AC unit. Our expertise extends to preventive maintenance, helping you avoid costly repairs and prolonging the lifespan of your system.",
    ar: "ص حلاصإو فيكم ءاوهلا ابحرم كب يف ةمدخ حلاصإ / ةنايص فيكم ،ءاوهلا ثيح دعي ديربت ةحاسملا ةصاخلا كب ،انتيولوأ عم انقيبطت لهس ،مادختسلاا كنكمي نأ لوقت اعادو مايلأل ةبطرلا يلايللاو يتلا لا مانت ببسب للخ يف تادحو فييكتلا . انيدل قيرف نم نيينفلا ءاربخلا درجم ةرقن ،ةدحاو ىلعو دادعتسا ةداعلإ دربلا ىلإ كلزنم وأ ك",
  },
  liftRepairing: {
    en: " Routine Maintenance:* Regular maintenance is essential for the longevity and performance of your lifts. Our technicians are proficient in conducting thorough inspections, lubrication, and adjustments to ensure optimal operation and safety compliance.",
    ar: " لقنلا ىلع ظافحلا يف هب قوثوملا ككيرش ،انيدل دعاصملا حلاصإ ةمدخ يف كب ابحرم دعاصملا حلاصإ ةنايص يذلا يدومعلا ،ةدوجلا ةيلاع ةمدخ ميدقت يف انينافتو انتربخ للاخ نم .ةسلاسب كب صاخلا ىنبملا كرحت ىلع ظفاحي نيميقملل ةحارلا ةدايزو قوثوم لكشب لمعلا نع فقوتلا تقو ليلقت عم ،ةءافكو نامأب كدعاصم لمعت نأ نمضن .نيرجأتسملاو ",
  },
  plumbing: {
    en: "Leak Detection and Repair: Our plumbers are experts in detecting and repairing leaks, whether it's a hidden pipe leak or a dripping faucet. We utilize advanced techniques and tools to pinpoint the source of the leak and provide efficient repair solutions.\n- Drain Cleaning and Unclogging: Clogged drains are no match for our plumbers. Using state-of-the-art equipment, we can quickly and effectively clear blockages in sinks, toilets, showers, and sewer lines, restoring proper drainage and preventing future issues.\n- Pipe Installation and Repair: From installing new pipes to repairing damaged ones, our plumbers have the skills and expertise to handle all your pipe-related needs. Whether it's copper, PVC, or PEX piping, we ensure proper installation and repair to maintain the integrity of your plumbing system.",
    ar: "كشف وإصلاح التسربات: سباكونا خبراء في كشف وإصلاح التسربات، سواء كان تسرب مخفي في الأنابيب أو صنبور يقطر. نستخدم تقنيات وأدوات متقدمة لتحديد مصدر التسرب وتقديم حلول إصلاح فعالة.\n- تنظيف وفك انسداد المجاري: انسداد المجاري لا يشكل أي مشكلة لسباكونا. باستخدام معدات متطورة، يمكننا بسرعة وفعالية إزالة الانسدادات في الأحواض والمراحيض والدش وخطوط الصرف الصحي، واستعادة الصرف السليم ومنع المشكلات المستقبلية.\n- تركيب وإصلاح الأنابيب: بدءًا من تركيب الأنابيب الجديدة إلى إصلاح التالفة، سباكونا يمتلكون المهارات والخبرة اللازمة للتعامل مع جميع احتياجات الأنابيب. سواء كانت الأنابيب من النحاس، PVC، أو PEX، نضمن التركيب والإصلاح الصحيحين للحفاظ على سلامة نظام السباكة الخاص بك.",
  },
  carpentry: {
    en: "- Custom Furniture: From statement pieces to functional furniture, our carpenters excel in crafting custom pieces tailored to your space and style.\n- Cabinetry and Shelving: Need storage solutions? Our expertise extends to designing and installing bespoke cabinetry and shelving that maximize space and enhance functionality.\n- Woodworking and Finishing: From intricate joinery to flawless finishes, our carpenters possess the skills and techniques to transform wood into works of art.",
    ar: " ثيثأت ىلإ علطتت تنك ءاوس .ةحارلا عم ةيفرحلا عمتجت ثيح ،انيدل ةراجنلا ةمدخ يف كب ابحرم ةراجنلا ةراجنلا عورشم عم لماعتلا وأ ،كتحاسم ديدجت وأ ،كلزنمDIY،  كتيؤر نوبلجي نيذلا ةرهملا نيراجنلاب كلصوي انقيبطت نإف ا ةيبشخلا لامعلأا ىلإ صصخملا ثاثلأا نم .ةايحلا ىلإ .عقاو ىلإ كراكفأ ليوحتل انه نحن ،ةدقعمل",
  },
  wallWorks: {
    en: "Painting and Finishing: Whether you're looking to refresh your walls with a new color or add decorative finishes, our painters are skilled in a variety of techniques to achieve the desired look and feel, from smooth and sleek to textured and dimensional.\n- Wallpaper Installation: Wallpaper adds personality and character to any space. Our experts specialize in precise wallpaper installation, ensuring patterns are aligned, seams are seamless, and edges are clean for a professional and polished finish.\n- Wall Repairs and Restoration: From minor touch-ups to extensive repairs, our team is proficient in repairing damaged walls, including cracks, holes, water damage, and wear and tear. We restore your walls to their former glory, ensuring structural integrity and aesthetic appeal.",
    ar: "أعمال الحوائط مرحباً بكم في خدمة أعمال الحوائط لدينا، حيث نقوم بتحويل جدرانكم إلى أعمال فنية. سواء كنت تتطلع إلى تجديد مساحتك بطبقة جديدة من الطالء، أو إضافة نسيج بورق حائط، أو تحسين األداء الوظيفي باستخدام التركيبات المثبتة على الحائط، فإن فريقنا من المحترفين المهرة موجود هنا إلضفاء الحيوية على رؤيتك، جدار واحد في كل مكان",
  },
  painter: {
    en: "Interior Painting: Whether you're refreshing a single room or painting the entire interior of your home or business, our painters have the expertise to deliver flawless results. From walls and ceilings to trim and doors, we ensure that every surface is painted to perfection.\n- Exterior Painting: Enhance your curb appeal and protect your property with our expert exterior painting services. From siding and stucco to decks and fences, our painters are skilled in surface preparation, priming, and painting techniques that withstand the elements and maintain their beauty for years to come.\n- Color Consultation: Not sure which colors will best suit your space? Our team offers professional color consultation services to help you choose the perfect palette for your project. Whether you're looking for classic neutrals, bold accents, or trendy hues, we'll help you find the perfect colors to express your style and personality.",
    ar: "رسام الرسم مرحبًا بك في خدمة الرسم االحترافية لدينا، حيث يلتقي اللون بالحرفية لتحويل المساحة الخاصة بك إلى عمل فني. سواء كنت تقوم بتجديد جدران منزلك، أو تحديث ديكور مكتبك، أو إضافة لمسة من األلوان إلى مساحة تجارية، فإن فريق الرسامين المهرة لدينا موجود هنا لتقديم نتائج استثنائية تتجاوز توقعاتك. ",
  },
  packersAndDroppers: {
    en: "Comprehensive Packing Services: Our team is skilled in packing all types of items,\nwe use high quality packing material and handle each item according to its fragility.\n\nEfficient Loading and Unloading: We employ trained professionals who handle the loading and unloading of your items with the utmost care,\nminimizing the risk of damage during transit.\n\nSafe and Secure Transportation: With our well-maintained fleet of vehicles,\nwe ensure that your possessions are transported safely to your new location.\n\nSpecialized Moving Services: We provide customized solutions for various moving needs,\nincluding residential moves, office relocations, and commercial moves.\nOur expertise extends to handling specialty items such as pianos, artwork, and antiques.\n\nUnpacking and Setup Assistance: Upon reaching your new location,\nwe offer unpacking services to help you settle in quickly.\nOur team can also assist with the setup and arrangement of your furniture and other items.\n\nExperience a hassle-free move with As-lahah,\nwhere we take care of every detail, so you can focus on starting your new chapter.",
    ar: "خدمات تعبئة شاملة: فريقنا ماهر في تعبئة جميع أنواع العناصر،\nنستخدم مواد تعبئة عالية الجودة ونتعامل مع كل عنصر وفقًا لهشاشته.\n\n*تحميل وتفريغ فعال:* نوظف محترفين مدربين يتعاملون مع تحميل وتفريغ العناصر الخاصة بك بعناية تامة،\nمما يقلل من خطر التلف أثناء النقل.\n\nنقل آمن ومضمون: مع أسطول مركباتنا المُصان جيدًا،\nنضمن أن تكون ممتلكاتك مُنقولة بأمان إلى موقعك الجديد.\n\nخدمات نقل متخصصة: نقدم حلول مخصصة لمختلف احتياجات النقل،\nبما في ذلك النقل السكني، وانتقال المكاتب، والنقل التجاري.\nتمتد خبرتنا إلى التعامل مع العناصر الخاصة مثل البيانو، والأعمال الفنية، والتحف.\n\nمساعدة في التفريغ والإعداد: عند الوصول إلى موقعك الجديد،\nنقدم خدمات التفريغ لمساعدتك على الاستقرار بسرعة.\nيمكن لفريقنا أيضًا المساعدة في إعداد وترتيب الأثاث والعناصر الأخرى.\n\nجرب الانتقال بدون عناء مع [اسم تطبيقك]،\nحيث نعتني بكل التفاصيل، حتى تتمكن من التركيز على بدء فصلك الجديد.",
  },
  electrician: {
    en: "Residential Electrical Services: Our electricians handle everything from minor repairs, such as fixing outlets and switches,\nto major projects like wiring upgrades and panel installations.\n\nElectrical Installations: Professional installation of new electrical systems and components,\nceiling fans.\n\nEmergency Services: Rapid response for electrical emergencies,\nensuring your safety and restoring power as quickly as possible.\n\nRely on our expert electricians to handle all your electrical needs with professionalism and precision,\nensuring your home or business operates safely and efficiently."
    ,
    ar:"خدمات الكهرباء السكنية: يتعامل كهربائيونا مع كل شيء من الإصلاحات الطفيفة، مثل إصلاح المنافذ والمفاتيح،\nإلى المشاريع الكبيرة مثل ترقيات الأسلاك وتركيب اللوحات.\n\nتركيبات كهربائية: تركيب احترافي للأنظمة والمكونات الكهربائية الجديدة،\nومراوح السقف.\n\nخدمات الطوارئ: استجابة سريعة لحالات الطوارئ الكهربائية،\nضمان سلامتك وإعادة التيار الكهربائي في أسرع وقت ممكن.\n\nاعتمد على كهربائيينا الخبراء للتعامل مع جميع احتياجاتك الكهربائية باحتراف ودقة،\nمما يضمن أن يعمل منزلك أو عملك بأمان وكفاءة."
    ,
  },
};