export default {
  acRepairing: {
    en: `<strong>AC Diagnosis and Troubleshooting:</strong> Our technicians have a keen eye for identifying AC issues and providing accurate diagnoses, saving you time and money on unnecessary repairs.<br><br><strong>Precision Repairs:</strong> From fixing refrigerant leaks to replacing faulty components, our technicians execute repairs with precision and attention to detail, ensuring long-lasting results.<br><br><strong>Preventive Maintenance:</strong> We believe in proactive care for your AC unit. Our expertise extends to preventive maintenance, helping you avoid costly repairs and prolonging the lifespan of your system.`,
    ar: "<strong>صيانة وإصلاح المكيفات الهوائية:</strong> يتمتع فنيونا بعين مدربة لتحديد مشاكل التكييف وتقديم تشخيص دقيق، مما يوفر لك الوقت والمال على الإصلاحات غير الضرورية.<br><br><strong>إصلاحات دقيقة:</strong> من إصلاح تسربات المبردات إلى استبدال المكونات الخاطئة، يقوم فنيونا بالإصلاح بدقة واهتمام بالتفاصيل، مما يضمن نتائج دائمة.<br><br><strong>الصيانة الوقائية:</strong> نحن نؤمن بالرعاية الوقائية لوحدة التكييف الخاصة بك. تمتد خبرتنا إلى الصيانة الوقائية، مما يساعدك على تجنب الإصلاحات الغالية وتمديد عمر نظامك.",
  },
  liftRepairing: {
    en: `<strong>Lift Diagnosis and Troubleshooting:</strong> Our technicians have a keen eye for identifying lift issues and providing accurate diagnoses, saving you time and money on unnecessary repairs.<br><br><strong>Precision Repairs:</strong> From fixing mechanical faults to replacing faulty components, our technicians execute repairs with precision and attention to detail, ensuring long-lasting results.<br><br><strong>Preventive Maintenance:</strong> We believe in proactive care for your lift. Our expertise extends to preventive maintenance, helping you avoid costly repairs and prolonging the lifespan of your system.<br><br><strong>Routine Maintenance:</strong> Regular maintenance is essential for the longevity and performance of your lifts. Our technicians are proficient in conducting thorough inspections, lubrication, and adjustments to ensure optimal operation and safety compliance.`,
    ar: "<strong>تشخيص وإصلاح المصاعد:</strong> فنيونا لديهم نظرة ثاقبة لتحديد مشاكل المصاعد وتقديم تشخيصات دقيقة، مما يوفر لك الوقت والمال على الإصلاحات غير الضرورية.<br><br><strong>إصلاحات دقيقة:</strong> من إصلاح الأعطال الميكانيكية إلى استبدال المكونات الخاطئة، يقوم فنيونا بالإصلاح بدقة واهتمام بالتفاصيل، مما يضمن نتائج دائمة.<br><br><strong>الصيانة الوقائية:</strong> نحن نؤمن بالرعاية الوقائية لمصعدك. تمتد خبرتنا إلى الصيانة الوقائية، مما يساعدك على تجنب الإصلاحات الغالية وتمديد عمر نظامك.<br><br><strong>الصيانة الدورية:</strong> الصيانة الدورية ضرورية لطول عمر وأداء المصاعد. يتقن فنيونا إجراء فحوصات شاملة، وتزييت، وضبط لضمان التشغيل الأمثل والامتثال للسلامة.",
  },
  plumbing: {
    en: `<strong>Leak Detection and Repair:</strong> Our plumbers are experts in detecting and repairing leaks, whether it's a hidden pipe leak or a dripping faucet. We utilize advanced techniques and tools to pinpoint the source of the leak and provide efficient repair solutions.<br><br><strong>Drain Cleaning and Unclogging:</strong> Clogged drains are no match for our plumbers. Using state-of-the-art equipment, we can quickly and effectively clear blockages in sinks, toilets, showers, and sewer lines, restoring proper drainage and preventing future issues.<br><br><strong>Pipe Installation and Repair:</strong> From installing new pipes to repairing damaged ones, our plumbers have the skills and expertise to handle all your pipe-related needs. Whether it's copper, PVC, or PEX piping, we ensure proper installation and repair to maintain the integrity of your plumbing system.`,
    ar: "<strong>كشف وإصلاح التسربات:</strong> سباكونا خبراء في كشف وإصلاح التسربات، سواء كان تسرب مخفي في الأنابيب أو صنبور يقطر. نستخدم تقنيات وأدوات متقدمة لتحديد مصدر التسرب وتقديم حلول إصلاح فعالة.<br><br><strong>تنظيف وفك انسداد المجاري:</strong> انسداد المجاري لا يشكل أي مشكلة لسباكونا. باستخدام معدات متطورة، يمكننا بسرعة وفعالية إزالة الانسدادات في الأحواض والمراحيض والدش وخطوط الصرف الصحي، واستعادة الصرف السليم ومنع المشكلات المستقبلية.<br><br><strong>تركيب وإصلاح الأنابيب:</strong> بدءًا من تركيب الأنابيب الجديدة إلى إصلاح التالفة، سباكونا يمتلكون المهارات والخبرة اللازمة للتعامل مع جميع احتياجات الأنابيب الخاصة بك. سواء كانت الأنابيب من النحاس، PVC، أو PEX، نضمن التركيب والإصلاح الصحيحين للحفاظ على سلامة نظام السباكة الخاص بك.",
  },
  carpentry: {
    en: `<strong>Custom Furniture:</strong> From statement pieces to functional furniture, our carpenters excel in crafting custom pieces tailored to your space and style.<br><br><strong>Cabinetry and Shelving:</strong> Need storage solutions? Our expertise extends to designing and installing bespoke cabinetry and shelving that maximize space and enhance functionality.<br><br><strong>Woodworking and Finishing:</strong> From intricate joinery to flawless finishes, our carpenters possess the skills and techniques to transform wood into works of art.`,
    ar: "<strong>أثاث مخصص:</strong> من القطع البارزة إلى الأثاث الوظيفي، يتفوق نجارونا في صناعة قطع مخصصة مصممة خصيصًا لمساحتك وأسلوبك.<br><br><strong>خزانات ورفوف:</strong> بحاجة إلى حلول تخزين؟ تمتد خبرتنا إلى تصميم وتركيب خزائن مخصصة ورفوف تعزز الفضاء وتعزز الوظائف.<br><br><strong>النجارة والتشطيب:</strong> من الوصلات المعقدة إلى التشطيبات الخالية من العيوب، يمتلك نجارونا المهارات والتقنيات لتحويل الخشب إلى أعمال فنية.",

  },
  wallWorks: {
    en: `<strong>Painting and Finishing:</strong> Whether you're looking to refresh your walls with a new color or add decorative finishes, our painters are skilled in a variety of techniques to achieve the desired look and feel, from smooth and sleek to textured and dimensional.<br><br><strong>Wallpaper Installation:</strong> Wallpaper adds personality and character to any space. Our experts specialize in precise wallpaper installation, ensuring patterns are aligned, seams are seamless, and edges are clean for a professional and polished finish.<br><br><strong>Wall Repairs and Restoration:</strong> From minor touch-ups to extensive repairs, our team is proficient in repairing damaged walls, including cracks, holes, water damage, and wear and tear. We restore your walls to their former glory, ensuring structural integrity and aesthetic appeal.`,
    ar: "<strong>الطلاء والتشطيب:</strong> سواء كنت تتطلع إلى تجديد جدرانك بلون جديد أو إضافة تشطيبات ديكورية، يتمتع رسامونا بمهارة في مجموعة متنوعة من التقنيات لتحقيق المظهر والشعور المرغوب به، من الناعم والأنيق إلى المتجعد والبعدي.<br><br><strong>تركيب ورق الجدران:</strong> يضيف ورق الجدران شخصية وطابعًا إلى أي مساحة. يتخصص خبراؤنا في تركيب ورق الجدران الدقيق، مضمنين مطابقة الأنماط، وجعل الخياطات سلسة، وجعل الحواف نظيفة للحصول على تشطيب احترافي ومصقول.<br><br><strong>إصلاح الجدران واستعادتها:</strong> من اللمسات البسيطة إلى الإصلاحات الشاملة، فريقنا ماهر في إصلاح الجدران التالفة، بما في ذلك الشقوق والثقوب وأضرار المياه والتآكل. نعيد جدرانك إلى مجدها السابق، مضمنين سلامة البنية وجاذبية الجمال."

  },
  painter: {
    en: `<strong>Interior Painting:</strong> Whether you're refreshing a single room or painting the entire interior of your home or business, our painters have the expertise to deliver flawless results. From walls and ceilings to trim and doors, we ensure that every surface is painted to perfection.<br><br><strong>Exterior Painting:</strong> Enhance your curb appeal and protect your property with our expert exterior painting services. From siding and stucco to decks and fences, our painters are skilled in surface preparation, priming, and painting techniques that withstand the elements and maintain their beauty for years to come.<br><br><strong>Color Consultation:</strong> Not sure which colors will best suit your space? Our team offers professional color consultation services to help you choose the perfect palette for your project. Whether you're looking for classic neutrals, bold accents, or trendy hues, we'll help you find the perfect colors to express your style and personality.`,
    ar: "<strong>الطلاء الداخلي:</strong> سواء كنت تقوم بتجديد غرفة واحدة أو بطلاء الداخلية بأكملها لمنزلك أو عملك، فإن رسامينا لديهم الخبرة لتقديم نتائج خالية من العيوب. من الجدران والأسقف إلى الزخارف والأبواب، نحرص على طلاء كل سطح بكمال.<br><br><strong>الطلاء الخارجي:</strong> قم بتعزيز جاذبية منزلك وحماية ممتلكاتك مع خدماتنا الخارجية المتخصصة في الطلاء. من الجوانب والطين إلى الشرفات والسياج، يتقن رسامونا تحضير السطوح والطبقة الأولية وتقنيات الطلاء التي تتحمل العوامل الجوية وتحافظ على جمالها لسنوات قادمة.<br><br><strong>استشارة الألوان:</strong> غير متأكد أي الألوان ستناسب مساحتك بشكل أفضل؟ يقدم فريقنا خدمات استشارية متخصصة في الألوان لمساعدتك في اختيار اللوحة المثالية لمشروعك. سواء كنت تبحث عن درجات ألوان كلاسيكية أو لمسات جريئة أو ألوان رائجة، سنساعدك في العثور على الألوان المثالية للتعبير عن أسلوبك وشخصيتك."

  },
  packersAndDroppers: {
    en: `<strong>Comprehensive Packing Services:</strong> Our team is skilled in packing all types of items, we use high quality packing material and handle each item according to its fragility.<br><br><strong>Efficient Loading and Unloading:</strong> We employ trained professionals who handle the loading and unloading of your items with the utmost care, minimizing the risk of damage during transit.<br><br><strong>Safe and Secure Transportation:</strong> With our well-maintained fleet of vehicles, we ensure that your possessions are transported safely to your new location.<br><br><strong>Specialized Moving Services:</strong> We provide customized solutions for various moving needs, including residential moves, office relocations, and commercial moves. Our expertise extends to handling specialty items such as pianos, artwork, and antiques.<br><br><strong>Unpacking and Setup Assistance:</strong> Upon reaching your new location, we offer unpacking services to help you settle in quickly. Our team can also assist with the setup and arrangement of your furniture and other items.<br><br>Experience a hassle-free move with As-lahah, where we take care of every detail, so you can focus on starting your new chapter.`,
    ar: "<strong>خدمات التعبئة الشاملة:</strong> فريقنا ماهر في تعبئة جميع أنواع العناصر، نستخدم مواد تعبئة عالية الجودة ونتعامل مع كل عنصر وفقًا لهشاشته.<br><br><strong>تحميل وتفريغ فعال:</strong> نوظف محترفين مدربين يتعاملون مع تحميل وتفريغ العناصر الخاصة بك بعناية تامة، مما يقلل من خطر التلف أثناء النقل.<br><br><strong>نقل آمن ومضمون:</strong> مع أسطول مركباتنا المُصان جيدًا، نضمن أن تكون ممتلكاتك مُنقولة بأمان إلى موقعك الجديد.<br><br><strong>خدمات نقل متخصصة:</strong> نقدم حلولًا مخصصة لمختلف احتياجات النقل، بما في ذلك النقل السكني، وانتقال المكاتب، والنقل التجاري. تمتد خبرتنا إلى التعامل مع العناصر الخاصة مثل البيانو، والأعمال الفنية، والتحف.<br><br><strong>مساعدة في التفريغ والإعداد:</strong> عند الوصول إلى موقعك الجديد، نقدم خدمات التفريغ لمساعدتك على الاستقرار بسرعة. يمكن لفريقنا أيضًا المساعدة في إعداد وترتيب الأثاث والعناصر الأخرى.<br><br>جرب الانتقال بدون عناء مع أس-لهاه، حيث نعتني بكل التفاصيل، حتى تتمكن من التركيز على بدء فصلك الجديد."

  },
  electrician: {
    en: `<strong>Residential Electrical Services:</strong> Our electricians handle everything from minor repairs, such as fixing outlets and switches, to major projects like wiring upgrades and panel installations.<br><br><strong>Electrical Installations:</strong> Professional installation of new electrical systems and components, ceiling fans.<br><br><strong>Emergency Services:</strong> Rapid response for electrical emergencies, ensuring your safety and restoring power as quickly as possible.<br><br>Rely on our expert electricians to handle all your electrical needs with professionalism and precision, ensuring your home or business operates safely and efficiently.`,
    ar: "<strong>خدمات الكهرباء السكنية:</strong> يتعامل كهربائيونا مع كل شيء من الإصلاحات الطفيفة، مثل إصلاح المنافذ والمفاتيح، إلى المشاريع الكبيرة مثل ترقيات الأسلاك وتركيب اللوحات.<br><br><strong>تركيبات كهربائية:</strong> تركيب احترافي للأنظمة والمكونات الكهربائية الجديدة، ومراوح السقف.<br><br><strong>خدمات الطوارئ:</strong> استجابة سريعة لحالات الطوارئ الكهربائية، ضمان سلامتك وإعادة التيار الكهربائي في أسرع وقت ممكن.<br><br>اعتمد على كهربائيينا الخبراء للتعامل مع جميع احتياجاتك الكهربائية باحتراف ودقة، مما يضمن أن يعمل منزلك أو عملك بأمان وكفاءة."

  },
};

